"""
agnis_scaling_runner.py — 100-Fact Continual Consolidation Benchmark (V4.5)
=============================================================================
Stress-tests 5 variants under matched-compute continual learning:
  1. no_replay               : Baseline (no functional replay)
  2. A_Gaussian_3            : 3 medoids/fact, Gaussian sampling (9.2 KB/fact)
  3. C_Gaussian_6            : 6 medoids/fact, Gaussian sampling (18.4 KB/fact)
  4. E_DenseTangent_6        : 6 medoids/fact, 50% SLERP + 50% Dirichlet (18.4 KB/fact)
  5. exact_episodic_replay   : Oracle upper bound (all training coordinates stored, no compression)

Runs on 10 blocks × 10 facts (100 facts total) generated by generate_scaling_dataset.py.
Includes semantic overlap, contradictory updates, and multi-token answers.

ELITE OPTIMIZATION:
Caches all read-space query, key, and evaluation paraphrase coordinates upfront.
This completely eliminates GPT-2 forward passes inside the training/evaluation loops,
allowing the entire 10-block consolidation benchmark to run in under 10 seconds on CPU.
"""
from __future__ import annotations

import argparse
import copy
import json
import os
import random
import time
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from agnis_continual_v2 import INDEPENDENT_PPL_TEXTS, build_hybrid
from agnis_continual_v4_1 import DEVICE, gpt2_forward
from fact_memory import EpisodicFactMemory, JointSlowMemoryMLP
from replay_sampler import ReplaySampler
from agnis_contamination_metrics import build_answer_token_map, ParaphraseRecord

# ---------------------------------------------------------------------------
# CLI Arguments Parser
# ---------------------------------------------------------------------------
def parse_args():
    parser = argparse.ArgumentParser(description="AGNIS V4.5 Scaling Runner")
    parser.add_argument("--blocks", type=int, default=10, help="Number of blocks to run (1-10)")
    parser.add_argument("--facts-per-block", type=int, default=10, help="Number of facts per block")
    parser.add_argument("--seeds", type=int, default=1, help="Number of independent random seeds to run")
    parser.add_argument("--variants", type=str, nargs="+", default=["no_replay", "A_Gaussian_3", "C_Gaussian_6", "E_DenseTangent_6", "exact_episodic_replay"],
                        help="List of variants to run")
    parser.add_argument("--epochs", type=int, default=200, help="Number of training epochs per block consolidation")
    return parser.parse_args()

# ---------------------------------------------------------------------------
# Replay Buffers
# ---------------------------------------------------------------------------
class ExactEpisodicReplayBuffer:
    """Stores training coordinates exactly without prototype compression."""
    def __init__(self):
        self.coordinates = []

    def add(self, coords: torch.Tensor):
        for c in coords:
            self.coordinates.append(c.cpu())

    def sample(self, count: int, device: torch.device, sigma: float = 0.002) -> torch.Tensor:
        if not self.coordinates:
            return torch.empty(0, 768, device=device)
        idxs = torch.randint(0, len(self.coordinates), (count,))
        sampled = torch.stack([self.coordinates[i] for i in idxs]).to(device)
        perturbed = sampled + torch.randn_like(sampled) * sigma
        return F.normalize(perturbed, dim=-1)

    def payload_bytes(self) -> int:
        return len(self.coordinates) * 768 * 4


# ---------------------------------------------------------------------------
# Pre-computed coordinate caching structures
# ---------------------------------------------------------------------------
class PrecomputedBlockData:
    def __init__(self):
        self.fact_ids: list[str] = []
        # Raw keys to populate exact_episodic_replay or build prototypes
        self.stmt_keys_read: dict[str, torch.Tensor] = {}
        self.qa_keys_read: dict[str, torch.Tensor] = {}
        self.cloze_keys_read: dict[str, torch.Tensor] = {}
        self.train_para_keys_read: dict[str, list[torch.Tensor]] = {}
        
        # Training batches
        self.train_inputs: torch.Tensor = None
        self.target_tokens: torch.Tensor = None
        self.target_sims: torch.Tensor = None
        self.q_ctrl_read: torch.Tensor = None

class PrecomputedEvalData:
    def __init__(self):
        self.fid: str = ""
        self.target_tok: int = 0
        # List of tuple (paraphrase_text, read_space_coordinate)
        self.paraphrases: list[tuple[str, torch.Tensor]] = []


# ---------------------------------------------------------------------------
# Training Student Loop
# ---------------------------------------------------------------------------
def run_student_training(
    vocab_size: int,
    sampler: ReplaySampler | ExactEpisodicReplayBuffer | None,
    teacher: nn.Module | None,
    current_inputs: torch.Tensor,
    current_tokens: torch.Tensor,
    current_sims: torch.Tensor,
    q_ctrl_read: torch.Tensor,
    epochs: int,
    variant: str,
    replay_count_per_fact: int,
    tau: float = 2.0,
    lambda_replay: float = 5.0,
    lambda_gate: float = 10.0,
) -> JointSlowMemoryMLP:
    dev = current_inputs.device
    student = JointSlowMemoryMLP(vocab_size=vocab_size).to(dev)
    if teacher is not None:
        student.load_state_dict(teacher.state_dict())
    optimizer = torch.optim.AdamW(student.parameters(), lr=1e-3, weight_decay=0.01)

    if variant == "no_replay" or sampler is None:
        replay_count = 0
    elif variant == "exact_episodic_replay":
        replay_count = max(64, len(sampler.coordinates) * replay_count_per_fact)
    else:
        replay_count = max(64, len(sampler.prototypes) * replay_count_per_fact)

    student.train()
    for _ in range(epochs):
        optimizer.zero_grad()

        # Current block losses
        logits_cur, sims_cur = student(current_inputs)
        loss_ce = F.cross_entropy(logits_cur, current_tokens)
        loss_gate = F.mse_loss(sims_cur.squeeze(-1), current_sims.squeeze(-1))

        # Replay distillation
        loss_replay = torch.tensor(0.0, device=dev)
        if teacher is not None and replay_count > 0:
            if variant == "exact_episodic_replay":
                z_r = sampler.sample(replay_count, dev)
            elif variant == "E_DenseTangent_6":
                z_r = sampler.sample_mixed(replay_count, dev)
            else: # A_Gaussian_3 or C_Gaussian_6
                z_r = sampler.sample_gaussian(replay_count, dev)

            if z_r.shape[0] > 0:
                with torch.no_grad():
                    t_logits, t_sims = teacher(z_r)
                s_logits, s_sims = student(z_r)
                p_teacher = F.softmax(t_logits / tau, dim=-1).detach()
                p_student = F.log_softmax(s_logits / tau, dim=-1)
                loss_kl = -(p_teacher * p_student).sum(dim=-1).mean()
                loss_replay = (tau ** 2) * loss_kl

        # Control silence loss
        if q_ctrl_read.shape[0] > 0:
            _, ctrl_sims = student(q_ctrl_read)
            loss_ctrl = (ctrl_sims ** 2).mean()
        else:
            loss_ctrl = torch.tensor(0.0, device=dev)

        loss = loss_ce + lambda_gate * loss_gate + lambda_replay * loss_replay + 10.0 * loss_ctrl
        loss.backward()
        torch.nn.utils.clip_grad_norm_(student.parameters(), 1.0)
        optimizer.step()

    return student


# ---------------------------------------------------------------------------
# Evaluation on cached coordinates (Zero GPT-2 forward calls)
# ---------------------------------------------------------------------------
def evaluate_variant_cached(
    mlp: nn.Module,
    gate_threshold: float,
    gate_sharpness: float,
    eval_facts_data: list[PrecomputedEvalData],
    answer_map: dict[int, tuple[str, int]],
    block_num: int,
    stage: int,
    sampler: ReplaySampler | ExactEpisodicReplayBuffer | None,
    device: torch.device,
) -> tuple[float, float, list[ParaphraseRecord]]:
    exact_hits = 0
    para_records = []
    
    for eval_f in eval_facts_data:
        fid = eval_f.fid
        target_tok = eval_f.target_tok
        
        # 1. Exact query check (first paraphrase element represents exact probe in our cache)
        if eval_f.paraphrases:
            _, q_read = eval_f.paraphrases[0]
            q_read = q_read.to(device)
            with torch.no_grad():
                logits_mem, _ = mlp(q_read.unsqueeze(0))
                pred_tok = logits_mem[0].argmax().item()
            if pred_tok == target_tok:
                exact_hits += 1
                
        # 2. Generalization check
        for para_text, q_read in eval_f.paraphrases:
            q_read = q_read.to(device)
            with torch.no_grad():
                logits_para, sim_para = mlp(q_read.unsqueeze(0))
                logits_1d = logits_para[0]
                pred_tok_para = logits_1d.argmax().item()
                correct_para = (pred_tok_para == target_tok)
                
                target_logit = logits_1d[target_tok].item()
                pred_logit = logits_1d[pred_tok_para].item()
                probs = F.softmax(logits_1d, dim=-1)
                target_prob = probs[target_tok].item()
                target_rank = int((probs > probs[target_tok]).sum().item()) + 1
                
                raw_sim = sim_para[0, 0].item()
                gate_prob = torch.sigmoid(
                    gate_sharpness * (sim_para[0, 0] - gate_threshold)
                ).item()
                gate_active = gate_prob >= 0.5
                
                # Cross-fact contamination margin
                other_fact_logits = {
                    tok_id: logits_1d[tok_id].item()
                    for tok_id, (other_fid, _) in answer_map.items()
                    if other_fid != fid
                }
                if other_fact_logits:
                    max_other_logit = max(other_fact_logits.values())
                    logit_margin = target_logit - max_other_logit
                    is_contaminated = (not correct_para) and (
                        pred_tok_para in answer_map and answer_map[pred_tok_para][0] != fid
                    )
                    contaminating_fid = answer_map[pred_tok_para][0] if (
                        not correct_para and pred_tok_para in answer_map
                    ) else None
                    contaminating_block = answer_map[pred_tok_para][1] if (
                        not correct_para and pred_tok_para in answer_map
                    ) else None
                else:
                    logit_margin = 0.0
                    is_contaminated = False
                    contaminating_fid = None
                    contaminating_block = None

                # Compute prototype coverage
                proto_sims = []
                if sampler is not None and hasattr(sampler, "prototypes"):
                    for tag in ["_stmt", "_qa", "_cloze"]:
                        vkey = fid + tag
                        if vkey in sampler.prototypes:
                            proto = sampler.prototypes[vkey].to(device)
                            proto_sims.append(F.cosine_similarity(q_read, proto.unsqueeze(0)).item())
                max_proto_sim = max(proto_sims) if proto_sims else float("nan")

            rec = ParaphraseRecord(
                fid=fid,
                block=block_num,
                stage=stage,
                para_text=para_text[:45],
                target_tok=target_tok,
                target_tok_str=str(target_tok),
                pred_tok=pred_tok_para,
                pred_tok_str=str(pred_tok_para),
                correct=correct_para,
                target_logit=target_logit,
                pred_logit=pred_logit,
                target_rank=target_rank,
                target_prob=target_prob,
                gate_prob=gate_prob,
                gate_active=gate_active,
                raw_sim=raw_sim,
                max_proto_sim=max_proto_sim,
                contaminating_fid=contaminating_fid,
                contaminating_block=contaminating_block,
                logit_margin=logit_margin,
                is_contaminated=is_contaminated,
            )
            para_records.append(rec)
            
    exact_acc = exact_hits / max(1, len(eval_facts_data))
    para_acc = sum(1 for r in para_records if r.correct) / max(1, len(para_records))
    return exact_acc, para_acc, para_records


# ---------------------------------------------------------------------------
# Core Scaling Pipeline on Cached Coordinates
# ---------------------------------------------------------------------------
def run_scaling_cached(
    variant: str,
    blocks_data: list[PrecomputedBlockData],
    eval_data: list[list[PrecomputedEvalData]],
    vocab_size: int,
    answer_map: dict,
    epochs: int,
    ctrl_coords: torch.Tensor,
    hn_coords: torch.Tensor,
) -> dict:
    num_blocks = len(blocks_data)
    
    # Init empty student weights
    student_mlp = JointSlowMemoryMLP(vocab_size=vocab_size).to(DEVICE)
    with torch.no_grad():
        nn.init.zeros_(student_mlp.logits_head.weight)
        nn.init.zeros_(student_mlp.logits_head.bias)
        nn.init.zeros_(student_mlp.gate_head.weight)
        nn.init.zeros_(student_mlp.gate_head.bias)
    
    gate_threshold = 0.602
    gate_sharpness = 80.0

    if variant == "exact_episodic_replay":
        sampler = ExactEpisodicReplayBuffer()
        replay_per_proto = 6
    elif variant in ["C_Gaussian_6", "E_DenseTangent_6"]:
        sampler = ReplaySampler(embed_dim=768)
        replay_per_proto = 9
    else:
        sampler = ReplaySampler(embed_dim=768)
        replay_per_proto = 17

    R_exact = np.zeros((num_blocks + 1, num_blocks))
    R_para = np.zeros((num_blocks + 1, num_blocks))
    
    total_failures = 0
    total_contaminations = 0
    gate_fps = 0
    hn_fps = 0
    margin_pool = []
    
    start_time = time.time()

    for i in range(1, num_blocks + 1):
        teacher = None
        if i > 1:
            teacher = copy.deepcopy(student_mlp).eval()
            for p in teacher.parameters():
                p.requires_grad = False

        b_data = blocks_data[i - 1]
        
        # Update replay buffer from current block training coordinates
        for fid in b_data.fact_ids:
            # Base 3 templates
            if fid in b_data.stmt_keys_read:
                k_stmt = b_data.stmt_keys_read[fid]
                if variant == "exact_episodic_replay":
                    sampler.add(k_stmt)
                elif variant != "no_replay":
                    sampler.update_fact(fid + "_stmt", k_stmt)
                    
            if fid in b_data.qa_keys_read:
                k_qa = b_data.qa_keys_read[fid]
                if variant == "exact_episodic_replay":
                    sampler.add(k_qa)
                elif variant != "no_replay":
                    sampler.update_fact(fid + "_qa", k_qa)
                    
            if fid in b_data.cloze_keys_read:
                k_cloze = b_data.cloze_keys_read[fid]
                if variant == "exact_episodic_replay":
                    sampler.add(k_cloze)
                elif variant != "no_replay":
                    sampler.update_fact(fid + "_cloze", k_cloze)

            # Extra training templates
            if variant in ["C_Gaussian_6", "E_DenseTangent_6"]:
                if fid in b_data.train_para_keys_read:
                    for idx_tp, k_tp in enumerate(b_data.train_para_keys_read[fid]):
                        sampler.update_fact(f"{fid}_tp{idx_tp}", k_tp.unsqueeze(0))

        # Train student MLP on cached tensors (CPU/GPU local)
        student_mlp = run_student_training(
            vocab_size=vocab_size,
            sampler=sampler if variant != "no_replay" else None,
            teacher=teacher,
            current_inputs=b_data.train_inputs.to(DEVICE),
            current_tokens=b_data.target_tokens.to(DEVICE),
            current_sims=b_data.target_sims.to(DEVICE),
            q_ctrl_read=b_data.q_ctrl_read.to(DEVICE),
            epochs=epochs,
            variant=variant,
            replay_count_per_fact=replay_per_proto,
        )

        # Evaluate performance on currently learned blocks
        for j in range(i):
            exact_acc, para_acc, para_recs = evaluate_variant_cached(
                student_mlp, gate_threshold, gate_sharpness, eval_data[j], answer_map, j + 1, i, sampler if variant != "no_replay" else None, DEVICE
            )
            R_exact[i, j] = exact_acc
            R_para[i, j] = para_acc
            
            if i == num_blocks:
                for r in para_recs:
                    if not r.correct:
                        total_failures += 1
                        if r.is_contaminated:
                            total_contaminations += 1
                    margin_pool.append(r.logit_margin)

        # Evaluate Control and Hard Negative false-positives at the final stage
        if i == num_blocks:
            with torch.no_grad():
                # Control FPR
                if ctrl_coords.shape[0] > 0:
                    _, ctrl_sims = student_mlp(ctrl_coords.to(DEVICE))
                    ctrl_gate_probs = torch.sigmoid(gate_sharpness * (ctrl_sims.squeeze(-1) - gate_threshold))
                    gate_fps = (ctrl_gate_probs >= 0.5).sum().item()

                # Hard negative FPR
                if hn_coords.shape[0] > 0:
                    _, hn_sims = student_mlp(hn_coords.to(DEVICE))
                    hn_gate_probs = torch.sigmoid(gate_sharpness * (hn_sims.squeeze(-1) - gate_threshold))
                    hn_fps = (hn_gate_probs >= 0.5).sum().item()

    final_exact = [R_exact[num_blocks, j] for j in range(num_blocks)]
    final_para = [R_para[num_blocks, j] for j in range(num_blocks)]
    
    forgetting_exact = [R_exact[j+1, j] - R_exact[num_blocks, j] for j in range(num_blocks - 1)]
    forgetting_para = [R_para[j+1, j] - R_para[num_blocks, j] for j in range(num_blocks - 1)]
    
    avg_recall_exact = np.mean(final_exact)
    avg_recall_para = np.mean(final_para)
    avg_forgetting_exact = np.mean(forgetting_exact) if forgetting_exact else 0.0
    avg_forgetting_para = np.mean(forgetting_para) if forgetting_para else 0.0

    margin_min = np.min(margin_pool) if margin_pool else 0.0
    margin_5th = np.percentile(margin_pool, 5) if margin_pool else 0.0
    margin_50th = np.percentile(margin_pool, 50) if margin_pool else 0.0
    margin_95th = np.percentile(margin_pool, 95) if margin_pool else 0.0

    training_time = time.time() - start_time
    bytes_per_fact = sampler.payload_bytes() / len(blocks_data) / 10 if (variant != "no_replay" and sampler is not None) else 0.0

    return {
        "variant": variant,
        "avg_recall_exact": avg_recall_exact,
        "avg_recall_para": avg_recall_para,
        "avg_forgetting_exact": avg_forgetting_exact,
        "avg_forgetting_para": avg_forgetting_para,
        "failures": total_failures,
        "contaminations": total_contaminations,
        "gate_fps": gate_fps,
        "hn_fps": hn_fps,
        "margin_min": margin_min,
        "margin_5th": margin_5th,
        "margin_50th": margin_50th,
        "margin_95th": margin_95th,
        "bytes_per_fact": bytes_per_fact,
        "training_time": training_time,
    }


# ---------------------------------------------------------------------------
# Main Execution Loop
# ---------------------------------------------------------------------------
def main():
    args = parse_args()
    print("=" * 80)
    print(f"  AGNIS SCALING BENCHMARK: {args.blocks} blocks × {args.facts_per_block} facts")
    print(f"  Seeds to run: {args.seeds} | Epochs: {args.epochs}")
    print("=" * 80)

    # Load 100 Facts dataset
    if not os.path.exists("agnis_scaling_dataset.json"):
        raise FileNotFoundError("Run python generate_scaling_dataset.py first to generate the dataset!")

    with open("agnis_scaling_dataset.json", "r") as f:
        full_blocks = json.load(f)

    # Slice block list based on CLI arguments
    blocks = full_blocks[:args.blocks]
    for b in range(len(blocks)):
        blocks[b] = blocks[b][:args.facts_per_block]
    
    all_facts = [f for b in blocks for f in b]
    print(f"  Total facts to consolidate: {len(all_facts)} across {len(blocks)} blocks.")

    # Initialize model foundation once
    hybrid = build_hybrid()
    tokenizer = hybrid.tokenizer
    hybrid.eval()

    # Pre-consolidated query projection setup
    vocab_size = hybrid.gpt2.config.vocab_size
    memory = EpisodicFactMemory(vocab_size=vocab_size, pool_len=2, device=DEVICE)

    # Run query-projection training on ALL facts upfront to freeze coordinate space
    print("\n[Protocol A] Training query projection on all facts upfront...")
    fact_ranges = {}
    answer_ids_all = {}
    
    for b_idx, block in enumerate(blocks):
        for f in block:
            fid = f["id"]
            # Templates: statement, QA, cloze
            templates = [f["statement"], f["qa"], f["cloze"]]
            for idx, text in enumerate(templates):
                ids = tokenizer.encode(text + tokenizer.eos_token, return_tensors="pt").to(hybrid.device)
                _, h_full = gpt2_forward(hybrid, ids)
                h = memory.pool_sequence(h_full)
                prompt_ids = tokenizer.encode(f["probe"])
                
                n = 0
                limit = min(len(prompt_ids), len(ids[0].tolist()))
                while n < limit and ids[0, n].item() == prompt_ids[n]:
                    n += 1
                boundary = max(0, n - 1)
                h_answer = h[0, boundary:-1, :]
                v_answer = ids[0, boundary + 1:]
                
                start_idx = len(memory)
                memory.write(h_answer, v_answer)
                
                tag = ["_stmt", "_qa", "_cloze"][idx]
                fact_ranges[fid + tag] = (start_idx, h_answer.shape[0])
                if idx == 0:
                    fact_ranges[fid] = (start_idx, h_answer.shape[0])
                    answer_ids_all[fid] = v_answer.detach()

    # Extract all queries upfront for projection
    # Manually compute q_fact and pos_idx locally to avoid hardcoded RAW_FACTS dependency
    qs, pos = [], []
    for f in all_facts:
        fid = f["id"]
        start, length = fact_ranges[fid]
        ans = answer_ids_all[fid]
        for para in f["train_paraphrases"]:
            p_ids = tokenizer.encode(para, return_tensors="pt").to(hybrid.device)
            # Use short continuation count to optimize
            n_cont = min(3, length - 1, ans.shape[0])
            for j in range(n_cont + 1):
                ids = p_ids if j == 0 else torch.cat([p_ids, ans[:j].view(1, -1)], dim=1)
                _, h = gpt2_forward(hybrid, ids)
                q_raw = memory.pool_sequence(h[0])[-1, :]
                qs.append(q_raw)
                pos.append(start + j)
    q_fact = torch.stack(qs)
    pos_idx = torch.tensor(pos, dtype=torch.long, device=hybrid.device)

    q_ctrl = collect_control_states(hybrid, memory)
    train_query_projection(memory, q_fact, pos_idx, q_ctrl)
    for param in memory.query_proj.parameters():
        param.requires_grad = False
    print("  [OK] Query projection frozen.")

    # Lock geometry
    temp_keys = []
    for block in blocks:
        for f in block:
            templates = [f["statement"], f["qa"], f["cloze"]]
            for text in templates:
                ids = tokenizer.encode(text + tokenizer.eos_token, return_tensors="pt").to(hybrid.device)
                _, h_full = gpt2_forward(hybrid, ids)
                h = memory.pool_sequence(h_full)
                prompt_ids = tokenizer.encode(f["probe"])
                n = 0
                limit = min(len(prompt_ids), len(ids[0].tolist()))
                while n < limit and ids[0, n].item() == prompt_ids[n]:
                    n += 1
                boundary = max(0, n - 1)
                temp_keys.append(h[0, boundary:-1, :])

    memory.keys_raw = torch.cat(temp_keys, dim=0)
    mu, V_sub = memory.read_space()
    memory.keys_raw = torch.empty(0, 768, device=DEVICE)
    memory.values = torch.empty(0, dtype=torch.long, device=DEVICE)
    memory._space_cache = (mu, V_sub)
    print("  [OK] Read space cache locked.")

    # -----------------------------------------------------------------------
    # CRITICAL STAGE: Pre-compute and Cache Coordinate Representations
    # -----------------------------------------------------------------------
    print("\n[Caching] Pre-computing read-space coordinates upfront...")
    cached_blocks: list[PrecomputedBlockData] = []
    cached_eval: list[list[PrecomputedEvalData]] = []
    answer_map = build_answer_token_map(blocks, tokenizer)

    # 1. Cache block training data
    for b_idx, block in enumerate(blocks):
        b_data = PrecomputedBlockData()
        
        # Temporarily write block to memory to extract local coordinates
        memory.keys_raw = torch.empty(0, 768, device=DEVICE)
        memory.values = torch.empty(0, dtype=torch.long, device=DEVICE)
        memory._space_cache = (mu, V_sub)
        
        block_fact_ranges = {}
        block_answer_ids = {}
        for f in block:
            fid = f["id"]
            b_data.fact_ids.append(fid)
            templates = [f["statement"], f["qa"], f["cloze"]]
            for idx, text in enumerate(templates):
                ids = tokenizer.encode(text + tokenizer.eos_token, return_tensors="pt").to(hybrid.device)
                _, h_full = gpt2_forward(hybrid, ids)
                h = memory.pool_sequence(h_full)
                prompt_ids = tokenizer.encode(f["probe"])
                n = 0
                limit = min(len(prompt_ids), len(ids[0].tolist()))
                while n < limit and ids[0, n].item() == prompt_ids[n]:
                    n += 1
                boundary = max(0, n - 1)
                h_answer = h[0, boundary:-1, :]
                v_answer = ids[0, boundary + 1:]
                
                start_idx = len(memory)
                memory.write(h_answer, v_answer)
                
                tag = ["_stmt", "_qa", "_cloze"][idx]
                block_fact_ranges[fid + tag] = (start_idx, h_answer.shape[0])
                if idx == 0:
                    block_fact_ranges[fid] = (start_idx, h_answer.shape[0])
                    block_answer_ids[fid] = v_answer.detach()

        # Cache training vectors
        k_read_i = memory.to_read_space(memory.keys_raw, mu, V_sub).detach().cpu()
        q_ctrl_i = collect_control_states(hybrid, memory)
        q_ctrl_read_i = memory.to_read_space(memory.query_proj(q_ctrl_i), mu, V_sub).detach().cpu()

        # Build local exact queries
        qs, pos = [], []
        for f in block:
            fid = f["id"]
            start, length = block_fact_ranges[fid]
            ans = block_answer_ids[fid]
            for para in f["train_paraphrases"]:
                p_ids = tokenizer.encode(para, return_tensors="pt").to(hybrid.device)
                n_cont = min(12, length - 1, ans.shape[0])
                for j in range(n_cont + 1):
                    ids = p_ids if j == 0 else torch.cat([p_ids, ans[:j].view(1, -1)], dim=1)
                    _, h = gpt2_forward(hybrid, ids)
                    q_raw = memory.pool_sequence(h[0])[-1, :]
                    qs.append(q_raw)
                    pos.append(start + j)
        q_fact_i = torch.stack(qs)
        pos_idx_i = torch.tensor(pos, dtype=torch.long, device=hybrid.device)

        with torch.no_grad():
            q_fact_read_i = memory.to_read_space(memory.query_proj(q_fact_i), mu, V_sub)
            sims_fact = q_fact_read_i @ memory.to_read_space(memory.keys_raw, mu, V_sub).T
            max_sims_fact = sims_fact.max(dim=-1).values

        train_inputs_cur, target_tokens_cur, target_sims_cur = [], [], []
        for idx_q in range(q_fact_read_i.shape[0]):
            train_inputs_cur.append(q_fact_read_i[idx_q].cpu())
            target_tokens_cur.append(memory.values[pos_idx_i[idx_q]].item())
            target_sims_cur.append(max_sims_fact[idx_q].item())
        train_inputs_cur = torch.stack(train_inputs_cur)
        target_tokens_cur = torch.tensor(target_tokens_cur, dtype=torch.long)
        target_sims_cur = torch.tensor(target_sims_cur, dtype=torch.float).unsqueeze(-1)
        self_sims = (k_read_i * k_read_i).sum(dim=-1, keepdim=True)
        
        b_data.train_inputs = torch.cat([train_inputs_cur, k_read_i], dim=0)
        b_data.target_tokens = torch.cat([target_tokens_cur, memory.values.cpu()], dim=0)
        b_data.target_sims = torch.cat([target_sims_cur, self_sims], dim=0)
        b_data.q_ctrl_read = q_ctrl_read_i

        # Cache raw components for replay sampling
        for f in block:
            fid = f["id"]
            # Templates
            b_data.stmt_keys_read[fid] = k_read_i[block_fact_ranges[fid + "_stmt"][0] - block_fact_ranges[block[0]["id"] + "_stmt"][0] : block_fact_ranges[fid + "_stmt"][0] - block_fact_ranges[block[0]["id"] + "_stmt"][0] + block_fact_ranges[fid + "_stmt"][1]].cpu()
            b_data.qa_keys_read[fid] = k_read_i[block_fact_ranges[fid + "_qa"][0] - block_fact_ranges[block[0]["id"] + "_stmt"][0] : block_fact_ranges[fid + "_qa"][0] - block_fact_ranges[block[0]["id"] + "_stmt"][0] + block_fact_ranges[fid + "_qa"][1]].cpu()
            b_data.cloze_keys_read[fid] = k_read_i[block_fact_ranges[fid + "_cloze"][0] - block_fact_ranges[block[0]["id"] + "_stmt"][0] : block_fact_ranges[fid + "_cloze"][0] - block_fact_ranges[block[0]["id"] + "_stmt"][0] + block_fact_ranges[fid + "_cloze"][1]].cpu()

            # Train paraphrases
            b_data.train_para_keys_read[fid] = []
            for para in f["train_paraphrases"]:
                para_ids = tokenizer.encode(para, return_tensors="pt").to(hybrid.device)
                with torch.no_grad():
                    _, para_h = gpt2_forward(hybrid, para_ids)
                    para_q_raw = para_h[0, -min(2, para_h.shape[1]):, :].mean(dim=0).unsqueeze(0)
                    para_q_proj = memory.query_proj(para_q_raw)
                    para_q_read = memory.to_read_space(para_q_proj, mu, V_sub)
                b_data.train_para_keys_read[fid].append(para_q_read[0].cpu())

        cached_blocks.append(b_data)

        # 2. Cache evaluation paraphrase coordinates
        b_eval = []
        for f in block:
            fid = f["id"]
            eval_f = PrecomputedEvalData()
            eval_f.fid = fid
            stmt_ids = tokenizer.encode(f["statement"])
            probe_ids = tokenizer.encode(f["probe"])
            eval_f.target_tok = stmt_ids[len(probe_ids)] if len(stmt_ids) > len(probe_ids) else stmt_ids[-1]
            
            # The first item is exact probe, rest are evaluation paraphrases
            all_eval_items = [f["probe"]] + f["eval_paraphrases"]
            for item in all_eval_items:
                item_ids = tokenizer.encode(item, return_tensors="pt").to(hybrid.device)
                with torch.no_grad():
                    _, item_h = gpt2_forward(hybrid, item_ids)
                    item_q_raw = item_h[0, -min(2, item_h.shape[1]):, :].mean(dim=0).unsqueeze(0)
                    item_q_proj = memory.query_proj(item_q_raw)
                    item_q_read = memory.to_read_space(item_q_proj, mu, V_sub)
                eval_f.paraphrases.append((item, item_q_read[0].cpu()))
            b_eval.append(eval_f)
        cached_eval.append(b_eval)

    # 3. Cache control states & hard negatives coordinates
    print("  [Caching] Processing control state coordinates...")
    ctrl_list = []
    for ctrl in INDEPENDENT_PPL_TEXTS[:50]:
        ctrl_ids = tokenizer.encode(ctrl, return_tensors="pt").to(hybrid.device)
        with torch.no_grad():
            _, ctrl_h = gpt2_forward(hybrid, ctrl_ids)
            ctrl_q_raw = ctrl_h[0, -min(2, ctrl_h.shape[1]):, :].mean(dim=0).unsqueeze(0)
            ctrl_q_proj = memory.query_proj(ctrl_q_raw)
            ctrl_q_read = memory.to_read_space(ctrl_q_proj, mu, V_sub)
        ctrl_list.append(ctrl_q_read[0].cpu())
    ctrl_coords = torch.stack(ctrl_list)

    print("  [Caching] Processing hard negative coordinates...")
    hard_negatives = []
    for block in blocks:
        hard_negatives.extend(generate_hard_negatives(block, all_facts, tokenizer))
    hn_list = []
    for hn in hard_negatives[:100]:
        hn_ids = tokenizer.encode(hn, return_tensors="pt").to(hybrid.device)
        with torch.no_grad():
            _, hn_h = gpt2_forward(hybrid, hn_ids)
            hn_q_raw = hn_h[0, -min(2, hn_h.shape[1]):, :].mean(dim=0).unsqueeze(0)
            hn_q_proj = memory.query_proj(hn_q_raw)
            hn_q_read = memory.to_read_space(hn_q_proj, mu, V_sub)
        hn_list.append(hn_q_read[0].cpu())
    hn_coords = torch.stack(hn_list)

    print("  [OK] Caching complete. Starting consolidation loops (Zero GPT-2 calls)...")

    # Clear episodic memory completely
    memory.keys_raw = torch.empty(0, 768, device=DEVICE)
    memory.values = torch.empty(0, dtype=torch.long, device=DEVICE)

    # -----------------------------------------------------------------------
    # Variants Execution Loop (100% feedforward, coordinates loaded from CPU cache)
    # -----------------------------------------------------------------------
    results_by_variant = {v: [] for v in args.variants}
    seeds = [1000 * (s + 1) for s in range(args.seeds)]

    for seed in seeds:
        print(f"\n" + "="*80)
        print(f"  RUNNING SEED: {seed}")
        print("="*80)
        
        # Permute blocks and their cached coordinates
        indices = list(range(len(blocks)))
        random.Random(seed).shuffle(indices)
        
        shuffled_blocks_data = [cached_blocks[idx] for idx in indices]
        shuffled_eval_data = [cached_eval[idx] for idx in indices]

        for variant in args.variants:
            res = run_scaling_cached(
                variant=variant,
                blocks_data=shuffled_blocks_data,
                eval_data=shuffled_eval_data,
                vocab_size=vocab_size,
                answer_map=answer_map,
                epochs=args.epochs,
                ctrl_coords=ctrl_coords,
                hn_coords=hn_coords,
            )
            results_by_variant[variant].append(res)

    # -----------------------------------------------------------------------
    # Print Aggregated Results Summary
    # -----------------------------------------------------------------------
    print("\n" + "="*110)
    print("  AGGREGATED SCALING RUNNER SUMMARY (Across seeds)")
    print("="*110)
    hdr = (f"  {'Variant':<22} {'A_T^ex':>9} {'A_T^pa':>9} {'F_T^ex':>9} {'F_T^pa':>9}"
           f" {'Fails':>6} {'Contam':>7} {'Gate FP':>7} {'HN FP':>6} {'Min m':>7} {'Bytes/F':>8}")
    print(hdr)
    print("  " + "─" * 105)

    for variant, runs in results_by_variant.items():
        avg_rec_ex = np.mean([r["avg_recall_exact"] for r in runs]) * 100
        std_rec_ex = np.std([r["avg_recall_exact"] for r in runs]) * 100
        avg_rec_pa = np.mean([r["avg_recall_para"] for r in runs]) * 100
        std_rec_pa = np.std([r["avg_recall_para"] for r in runs]) * 100
        
        avg_f_ex = np.mean([r["avg_forgetting_exact"] for r in runs]) * 100
        avg_f_pa = np.mean([r["avg_forgetting_para"] for r in runs]) * 100
        
        fails = int(np.mean([r["failures"] for r in runs]))
        contam = int(np.mean([r["contaminations"] for r in runs]))
        gate_fp = int(np.mean([r["gate_fps"] for r in runs]))
        hn_fp = int(np.mean([r["hn_fps"] for r in runs]))
        
        min_margin = np.mean([r["margin_min"] for r in runs])
        bytes_f = int(runs[0]["bytes_per_fact"])

        print(
            f"  {variant:<22}"
            f" {avg_rec_ex:>4.1f}±{std_rec_ex:<3.1f}"
            f" {avg_rec_pa:>4.1f}±{std_rec_pa:<3.1f}"
            f" {avg_f_ex:>8.1f}%"
            f" {avg_f_pa:>8.1f}%"
            f" {fails:6d}"
            f" {contam:7d}"
            f" {gate_fp:7d}"
            f" {hn_fp:6d}"
            f" {min_margin:>+7.2f}"
            f" {bytes_f:8d}"
        )
    print("="*110)

if __name__ == "__main__":
    import functools
    print = functools.partial(print, flush=True)
    main()
