"""
agnis_scaling_runner.py — 100-Fact Continual Consolidation Benchmark (V4.5)
=============================================================================
Stress-tests 5 variants under matched-compute continual learning:
  1. no_replay               : Baseline (no functional replay)
  2. A_Gaussian_3            : 3 medoids/fact, Gaussian sampling (9.2 KB/fact)
  3. C_Gaussian_6            : 6 medoids/fact, Gaussian sampling (18.4 KB/fact)
  4. E_DenseTangent_6        : 6 medoids/fact, 50% SLERP + 50% Dirichlet (18.4 KB/fact)
  5. exact_episodic_replay   : Oracle upper bound (all training coordinates stored, no compression)

Runs on 10 blocks × 10 facts (100 facts total) generated by generate_scaling_dataset.py.
Includes semantic overlap, contradictory updates, and multi-token answers.
Reports margins (min, 5th, 50th, 95th percentiles), contamination rate, and gate FPR.
"""
from __future__ import annotations

import argparse
import copy
import json
import os
import random
import time
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from agnis_continual_v2 import INDEPENDENT_PPL_TEXTS, build_hybrid
from agnis_continual_v4_1 import DEVICE, gpt2_forward, measure_ppl
from agnis_continual_v4_2 import collect_control_states, train_query_projection
from fact_memory import EpisodicFactMemory, JointSlowMemoryMLP
from replay_sampler import ReplaySampler, slerp
from agnis_contamination_metrics import build_answer_token_map, ParaphraseRecord

# ---------------------------------------------------------------------------
# CLI Arguments Parser
# ---------------------------------------------------------------------------
def parse_args():
    parser = argparse.ArgumentParser(description="AGNIS V4.5 Scaling Runner")
    parser.add_argument("--blocks", type=int, default=10, help="Number of blocks to run (1-10)")
    parser.add_argument("--facts-per-block", type=int, default=10, help="Number of facts per block")
    parser.add_argument("--seeds", type=int, default=1, help="Number of independent random seeds to run")
    parser.add_argument("--variants", type=str, nargs="+", default=["no_replay", "A_Gaussian_3", "C_Gaussian_6", "E_DenseTangent_6", "exact_episodic_replay"],
                        help="List of variants to run")
    parser.add_argument("--epochs", type=int, default=200, help="Number of training epochs per block consolidation")
    return parser.parse_args()

# ---------------------------------------------------------------------------
# Oracle/Episodic Replay Buffer (for the upper bound)
# ---------------------------------------------------------------------------
class ExactEpisodicReplayBuffer:
    """Stores every training coordinate exactly without prototype compression."""
    def __init__(self):
        self.coordinates = [] # List of Tensors (cpu)

    def add(self, coords: torch.Tensor):
        for c in coords:
            self.coordinates.append(c.cpu())

    def sample(self, count: int, device: torch.device, sigma: float = 0.002) -> torch.Tensor:
        if not self.coordinates:
            return torch.empty(0, 768, device=device)
        idxs = torch.randint(0, len(self.coordinates), (count,))
        sampled = torch.stack([self.coordinates[i] for i in idxs]).to(device)
        # Add small perturbation on the unit hypersphere
        perturbed = sampled + torch.randn_like(sampled) * sigma
        return F.normalize(perturbed, dim=-1)

    def payload_bytes(self) -> int:
        return len(self.coordinates) * 768 * 4

# ---------------------------------------------------------------------------
# Local Query Collection for Scaling Dataset
# ---------------------------------------------------------------------------
@torch.no_grad()
def collect_scaling_fact_queries(
    hybrid,
    memory: EpisodicFactMemory,
    fact_ranges: dict,
    answer_ids: dict,
    all_facts: list[dict],
    max_cont_tokens: int = 3,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Local, scaling-aware version of collect_fact_queries."""
    tok = hybrid.tokenizer
    qs, pos = [], []
    for f in all_facts:
        fid = f["id"]
        start, length = fact_ranges[fid]
        ans = answer_ids[fid]
        for para in f["train_paraphrases"]:
            p_ids = tok.encode(para, return_tensors="pt").to(hybrid.device)
            n_cont = min(max_cont_tokens, length - 1, ans.shape[0])
            for j in range(n_cont + 1):
                ids = p_ids if j == 0 else torch.cat(
                    [p_ids, ans[:j].view(1, -1)], dim=1
                )
                _, h = gpt2_forward(hybrid, ids)
                # last hidden pooled sequences
                q_raw = memory.pool_sequence(h[0])[-1, :]
                qs.append(q_raw)
                pos.append(start + j)
    return torch.stack(qs), torch.tensor(pos, dtype=torch.long, device=hybrid.device)

@torch.no_grad()
def collect_scaling_block_queries(
    hybrid,
    memory: EpisodicFactMemory,
    block_facts: list[dict],
    fact_ranges: dict,
    answer_ids: dict,
    max_cont_tokens: int = 12,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Local, scaling-aware version of collect_block_queries."""
    tok = hybrid.tokenizer
    qs, pos = [], []
    for f in block_facts:
        fid = f["id"]
        start, length = fact_ranges[fid]
        ans = answer_ids[fid]
        for para in f["train_paraphrases"]:
            p_ids = tok.encode(para, return_tensors="pt").to(hybrid.device)
            n_cont = min(max_cont_tokens, length - 1, ans.shape[0])
            for j in range(n_cont + 1):
                ids = p_ids if j == 0 else torch.cat(
                    [p_ids, ans[:j].view(1, -1)], dim=1
                )
                _, h = gpt2_forward(hybrid, ids)
                T = h.shape[1]
                q_pooled = h[0, -min(2, T):, :].mean(dim=0)
                qs.append(q_pooled)
                pos.append(start + j)
    return torch.stack(qs), torch.tensor(pos, dtype=torch.long, device=hybrid.device)

# ---------------------------------------------------------------------------
# Hard Negatives Generation on the fly
# ---------------------------------------------------------------------------
def generate_hard_negatives(block_facts: list[dict], all_facts: list[dict], tokenizer) -> list[str]:
    """Generates entity-swapped hard negatives from the fact pool to stress-test gating specificity."""
    negatives = []
    # Collect all capitals and compounds in the universe to swap
    capitals = list(set(f["capital"] for f in all_facts if "capital" in f))
    temperatures = list(set(f["temperature"] for f in all_facts if "temperature" in f))
    periods = list(set(f["period"] for f in all_facts if "period" in f))

    for f in block_facts:
        if f["category"] == "geography":
            # Swap capital
            alt_caps = [c for c in capitals if c != f["capital"]]
            if alt_caps:
                negatives.append(f"{random.choice(alt_caps)} is the official capital city of the region of {f['location']}.")
        elif f["category"] == "science":
            # Swap temperature
            alt_temps = [t for t in temperatures if t != f["temperature"]]
            if alt_temps:
                negatives.append(f"The molecular compound {f['compound']} liquefies at exactly {random.choice(alt_temps)} degrees Celsius.")
        elif f["category"] == "astronomy":
            # Swap period
            alt_periods = [p for p in periods if p != f["period"]]
            if alt_periods:
                negatives.append(f"The planetary satellite {f['moon']} orbits {f['planet']} in exactly {random.choice(alt_periods)} days.")
    return negatives

# ---------------------------------------------------------------------------
# Evaluation function
# ---------------------------------------------------------------------------
def evaluate_variant_performance(
    hybrid,
    memory: EpisodicFactMemory,
    mu: torch.Tensor,
    V_sub: torch.Tensor | None,
    block_facts: list[dict],
    answer_map: dict[int, tuple[str, int]],
    block_num: int,
    stage: int,
    sampler: ReplaySampler | ExactEpisodicReplayBuffer | None,
) -> tuple[float, float, list[ParaphraseRecord]]:
    """Evaluates exact recall, paraphrase recall, logit margin, and returns paraphrase records."""
    tokenizer = hybrid.tokenizer
    device = hybrid.device
    
    exact_hits = 0
    para_records = []
    
    for f in block_facts:
        fid = f["id"]
        # 1. Exact Recall Check
        ids = tokenizer.encode(f["probe"], return_tensors="pt").to(device)
        with torch.no_grad():
            _, h = gpt2_forward(hybrid, ids)
            q_raw = h[0, -min(2, h.shape[1]):, :].mean(dim=0).unsqueeze(0)
            q_proj = memory.query_proj(q_raw)
            q_read = memory.to_read_space(q_proj, mu, V_sub)
            logits_mem, sim_val = memory.slow_mlp(q_read)
            pred_tok = logits_mem[0].argmax().item()
            
        stmt_ids = tokenizer.encode(f["statement"])
        probe_ids = tokenizer.encode(f["probe"])
        target_tok = stmt_ids[len(probe_ids)] if len(stmt_ids) > len(probe_ids) else stmt_ids[-1]
        
        if pred_tok == target_tok:
            exact_hits += 1
            
        # 2. Paraphrase Generalization & Contamination evaluation
        eval_paras = f["eval_paraphrases"]
        for para in eval_paras:
            ids_para = tokenizer.encode(para, return_tensors="pt").to(device)
            with torch.no_grad():
                _, h_para = gpt2_forward(hybrid, ids_para)
                q_raw_para = h_para[0, -min(2, h_para.shape[1]):, :].mean(dim=0).unsqueeze(0)
                q_proj_para = memory.query_proj(q_raw_para)
                q_read_para = memory.to_read_space(q_proj_para, mu, V_sub)
                logits_para, sim_para = memory.slow_mlp(q_read_para)
                
                logits_1d = logits_para[0]
                pred_tok_para = logits_1d.argmax().item()
                correct_para = (pred_tok_para == target_tok)
                
                target_logit = logits_1d[target_tok].item()
                pred_logit = logits_1d[pred_tok_para].item()
                probs = F.softmax(logits_1d, dim=-1)
                target_prob = probs[target_tok].item()
                target_rank = int((probs > probs[target_tok]).sum().item()) + 1
                
                raw_sim = sim_para[0, 0].item()
                gate_prob = torch.sigmoid(
                    memory.gate_sharpness * (sim_para[0, 0] - memory.gate_threshold)
                ).item()
                gate_active = gate_prob >= 0.5
                
                # Check for cross-fact contamination margin
                other_fact_logits = {
                    tok_id: logits_1d[tok_id].item()
                    for tok_id, (other_fid, _) in answer_map.items()
                    if other_fid != fid
                }
                if other_fact_logits:
                    max_other_logit = max(other_fact_logits.values())
                    logit_margin = target_logit - max_other_logit
                    is_contaminated = (not correct_para) and (
                        pred_tok_para in answer_map and answer_map[pred_tok_para][0] != fid
                    )
                    contaminating_fid = answer_map[pred_tok_para][0] if (
                        not correct_para and pred_tok_para in answer_map
                    ) else None
                    contaminating_block = answer_map[pred_tok_para][1] if (
                        not correct_para and pred_tok_para in answer_map
                    ) else None
                else:
                    logit_margin = 0.0
                    is_contaminated = False
                    contaminating_fid = None
                    contaminating_block = None

                # Compute prototype coverage
                proto_sims = []
                if sampler is not None and hasattr(sampler, "prototypes"):
                    for tag in ["_stmt", "_qa", "_cloze"]:
                        vkey = fid + tag
                        if vkey in sampler.prototypes:
                            proto = sampler.prototypes[vkey].to(device)
                            proto_sims.append(F.cosine_similarity(q_read_para, proto.unsqueeze(0)).item())
                max_proto_sim = max(proto_sims) if proto_sims else float("nan")

            rec = ParaphraseRecord(
                fid=fid,
                block=block_num,
                stage=stage,
                para_text=para[:45],
                target_tok=target_tok,
                target_tok_str=tokenizer.decode([target_tok]),
                pred_tok=pred_tok_para,
                pred_tok_str=tokenizer.decode([pred_tok_para]),
                correct=correct_para,
                target_logit=target_logit,
                pred_logit=pred_logit,
                target_rank=target_rank,
                target_prob=target_prob,
                gate_prob=gate_prob,
                gate_active=gate_active,
                raw_sim=raw_sim,
                max_proto_sim=max_proto_sim,
                contaminating_fid=contaminating_fid,
                contaminating_block=contaminating_block,
                logit_margin=logit_margin,
                is_contaminated=is_contaminated,
            )
            para_records.append(rec)
            
    exact_acc = exact_hits / len(block_facts)
    para_acc = sum(1 for r in para_records if r.correct) / len(para_records)
    return exact_acc, para_acc, para_records

# ---------------------------------------------------------------------------
# Training Student Loop with Ablation Logic
# ---------------------------------------------------------------------------
def run_student_training(
    memory: EpisodicFactMemory,
    sampler: ReplaySampler | ExactEpisodicReplayBuffer | None,
    teacher: nn.Module | None,
    current_inputs: torch.Tensor,
    current_tokens: torch.Tensor,
    current_sims: torch.Tensor,
    q_ctrl_read: torch.Tensor,
    epochs: int,
    variant: str,
    replay_count_per_fact: int,
    tau: float = 2.0,
    lambda_replay: float = 5.0,
    lambda_gate: float = 10.0,
) -> JointSlowMemoryMLP:
    dev = current_inputs.device
    student = JointSlowMemoryMLP(vocab_size=memory.vocab_size).to(dev)
    if teacher is not None:
        student.load_state_dict(teacher.state_dict())
    optimizer = torch.optim.AdamW(student.parameters(), lr=1e-3, weight_decay=0.01)

    # Matched replay count calculation
    if variant == "no_replay" or sampler is None:
        replay_count = 0
    elif variant == "exact_episodic_replay":
        replay_count = max(64, len(sampler.coordinates) * replay_count_per_fact)
    else:
        replay_count = max(64, len(sampler.prototypes) * replay_count_per_fact)

    student.train()
    for _ in range(epochs):
        optimizer.zero_grad()

        # Current block losses
        logits_cur, sims_cur = student(current_inputs)
        loss_ce = F.cross_entropy(logits_cur, current_tokens)
        loss_gate = F.mse_loss(sims_cur.squeeze(-1), current_sims.squeeze(-1))

        # Replay distillation
        loss_replay = torch.tensor(0.0, device=dev)
        if teacher is not None and replay_count > 0:
            if variant == "exact_episodic_replay":
                z_r = sampler.sample(replay_count, dev)
            elif variant == "E_DenseTangent_6":
                z_r = sampler.sample_mixed(replay_count, dev)
            else: # A_Gaussian_3 or C_Gaussian_6
                z_r = sampler.sample_gaussian(replay_count, dev)

            if z_r.shape[0] > 0:
                with torch.no_grad():
                    t_logits, t_sims = teacher(z_r)
                s_logits, s_sims = student(z_r)
                p_teacher = F.softmax(t_logits / tau, dim=-1).detach()
                p_student = F.log_softmax(s_logits / tau, dim=-1)
                loss_kl = -(p_teacher * p_student).sum(dim=-1).mean()
                loss_replay = (tau ** 2) * loss_kl

        # Control silence loss
        if q_ctrl_read.shape[0] > 0:
            _, ctrl_sims = student(q_ctrl_read)
            loss_ctrl = (ctrl_sims ** 2).mean()
        else:
            loss_ctrl = torch.tensor(0.0, device=dev)

        loss = loss_ce + lambda_gate * loss_gate + lambda_replay * loss_replay + 10.0 * loss_ctrl
        loss.backward()
        torch.nn.utils.clip_grad_norm_(student.parameters(), 1.0)
        optimizer.step()

    return student

# ---------------------------------------------------------------------------
# Core Scaling Pipeline
# ---------------------------------------------------------------------------
def run_scaling_experiment(
    variant: str,
    blocks: list[list[dict]],
    hybrid,
    base_memory: EpisodicFactMemory,
    mu: torch.Tensor,
    V_sub: torch.Tensor | None,
    all_facts: list[dict],
    epochs: int,
) -> dict:
    """Run continual learning scaling across all blocks for a variant."""
    tokenizer = hybrid.tokenizer
    num_blocks = len(blocks)
    
    # Initialize fresh model copy for this run
    memory = EpisodicFactMemory(vocab_size=base_memory.vocab_size, pool_len=2, device=DEVICE)
    memory.query_proj.load_state_dict(base_memory.query_proj.state_dict())
    for param in memory.query_proj.parameters():
        param.requires_grad = False
    memory._space_cache = (mu, V_sub)
    memory.gate_threshold = base_memory.gate_threshold
    memory.gate_sharpness = base_memory.gate_sharpness
    
    empty_mlp = JointSlowMemoryMLP(vocab_size=base_memory.vocab_size).to(DEVICE)
    with torch.no_grad():
        nn.init.zeros_(empty_mlp.logits_head.weight)
        nn.init.zeros_(empty_mlp.logits_head.bias)
        nn.init.zeros_(empty_mlp.gate_head.weight)
        nn.init.zeros_(empty_mlp.gate_head.bias)
    memory.slow_mlp = empty_mlp
    
    # Select Replay Buffer / Sampler
    if variant == "exact_episodic_replay":
        sampler = ExactEpisodicReplayBuffer()
        replay_per_proto = 6 # upper bound matched
    elif variant in ["C_Gaussian_6", "E_DenseTangent_6"]:
        sampler = ReplaySampler(embed_dim=768)
        replay_per_proto = 9 # matched density
    else: # A_Gaussian_3
        sampler = ReplaySampler(embed_dim=768)
        replay_per_proto = 17 # 17 * 3 = 51 ≈ matched
        
    answer_map = build_answer_token_map(blocks, tokenizer)
    
    R_exact = np.zeros((num_blocks + 1, num_blocks))
    R_para = np.zeros((num_blocks + 1, num_blocks))
    
    # Control state evaluation variables
    control_texts = INDEPENDENT_PPL_TEXTS[:50]
    hard_negatives = []
    
    total_failures = 0
    total_contaminations = 0
    gate_fps = 0
    hn_fps = 0
    margin_pool = []
    
    start_time = time.time()

    for i in range(1, num_blocks + 1):
        teacher = None
        if i > 1:
            teacher = copy.deepcopy(memory.slow_mlp).eval()
            for p in teacher.parameters():
                p.requires_grad = False

        block_facts = blocks[i - 1]
        
        # Build hard negatives for metrics
        hard_negatives.extend(generate_hard_negatives(block_facts, all_facts, tokenizer))
        
        # Inject fact injection templates
        block_fact_ranges = {}
        block_answer_ids = {}
        
        for f in block_facts:
            fid = f["id"]
            # Templates: statement, QA, cloze
            templates = [f["statement"], f["qa"], f["cloze"]]
            for idx, text in enumerate(templates):
                ids = tokenizer.encode(text + tokenizer.eos_token, return_tensors="pt").to(hybrid.device)
                _, h_full = gpt2_forward(hybrid, ids)
                h = memory.pool_sequence(h_full)
                prompt_ids = tokenizer.encode(f["probe"]) # use probe to split answer
                
                n = 0
                limit = min(len(prompt_ids), len(ids[0].tolist()))
                while n < limit and ids[0, n].item() == prompt_ids[n]:
                    n += 1
                boundary = max(0, n - 1)
                h_answer = h[0, boundary:-1, :]
                v_answer = ids[0, boundary + 1:]
                
                start_idx = len(memory)
                memory.write(h_answer, v_answer)
                
                tag = ["_stmt", "_qa", "_cloze"][idx]
                block_fact_ranges[fid + tag] = (start_idx, h_answer.shape[0])
                if idx == 0:
                    block_fact_ranges[fid] = (start_idx, h_answer.shape[0])
                    block_answer_ids[fid] = v_answer.detach()

        q_fact_i, pos_idx_i = collect_scaling_block_queries(
            hybrid, memory, block_facts, block_fact_ranges, block_answer_ids
        )
        q_ctrl_i = collect_control_states(hybrid, memory)

        # Update replay sampler/buffer
        for f in block_facts:
            fid = f["id"]
            # Base 3 templates
            for tag in ["_stmt", "_qa", "_cloze"]:
                vkey = fid + tag
                if vkey in block_fact_ranges:
                    start, length = block_fact_ranges[vkey]
                    key_slice = memory.keys_raw[start : start + length]
                    if key_slice.shape[0] > 0:
                        with torch.no_grad():
                            key_read = memory.to_read_space(key_slice, mu, V_sub)
                        
                        if variant == "exact_episodic_replay":
                            sampler.add(key_read)
                        elif variant != "no_replay":
                            sampler.update_fact(vkey, key_read)

            # Extra training-only templates for C_Gaussian_6 and E_DenseTangent_6
            if variant in ["C_Gaussian_6", "E_DenseTangent_6"]:
                train_paras = f["train_paraphrases"]
                for p_idx, para in enumerate(train_paras):
                    para_ids = tokenizer.encode(para, return_tensors="pt").to(hybrid.device)
                    with torch.no_grad():
                        _, para_h = gpt2_forward(hybrid, para_ids)
                        para_q_raw = para_h[0, -min(2, para_h.shape[1]):, :].mean(dim=0).unsqueeze(0)
                        para_q_proj = memory.query_proj(para_q_raw)
                        para_q_read = memory.to_read_space(para_q_proj, mu, V_sub)
                    
                    vkey = f"{fid}_tp{p_idx}"
                    sampler.update_fact(vkey, para_q_read)

        # Build training batches
        k_read_i = memory.to_read_space(memory.keys_raw, mu, V_sub).detach()
        q_ctrl_read_i = memory.to_read_space(memory.query_proj(q_ctrl_i), mu, V_sub).detach()

        train_inputs_cur, target_tokens_cur, target_sims_cur = [], [], []
        with torch.no_grad():
            q_fact_read_i = memory.to_read_space(memory.query_proj(q_fact_i), mu, V_sub)
            sims_fact = q_fact_read_i @ k_read_i.T
            max_sims_fact = sims_fact.max(dim=-1).values
        for idx_q in range(q_fact_read_i.shape[0]):
            train_inputs_cur.append(q_fact_read_i[idx_q])
            target_tokens_cur.append(memory.values[pos_idx_i[idx_q]].item())
            target_sims_cur.append(max_sims_fact[idx_q].item())
        train_inputs_cur = torch.stack(train_inputs_cur).to(DEVICE)
        target_tokens_cur = torch.tensor(target_tokens_cur, dtype=torch.long, device=DEVICE)
        target_sims_cur = torch.tensor(target_sims_cur, dtype=torch.float, device=DEVICE).unsqueeze(-1)
        self_sims = (k_read_i * k_read_i).sum(dim=-1, keepdim=True)
        train_inputs_cur = torch.cat([train_inputs_cur, k_read_i], dim=0)
        target_tokens_cur = torch.cat([target_tokens_cur, memory.values], dim=0)
        target_sims_cur = torch.cat([target_sims_cur, self_sims], dim=0)

        # Train student MLP
        memory.slow_mlp = run_student_training(
            memory=memory,
            sampler=sampler if variant != "no_replay" else None,
            teacher=teacher,
            current_inputs=train_inputs_cur,
            current_tokens=target_tokens_cur,
            current_sims=target_sims_cur,
            q_ctrl_read=q_ctrl_read_i,
            epochs=epochs,
            variant=variant,
            replay_count_per_fact=replay_per_proto,
        )

        # Evict episodic database completely
        memory.keys_raw = torch.empty(0, 768, device=DEVICE)
        memory.values = torch.empty(0, dtype=torch.long, device=DEVICE)
        memory._space_cache = (mu, V_sub)
        memory.gate_threshold = 0.602
        memory.gate_sharpness = 80.0

        # Evaluate performance on currently learned blocks
        for j in range(i):
            exact_acc, para_acc, para_recs = evaluate_variant_performance(
                hybrid, memory, mu, V_sub, blocks[j], answer_map, j + 1, i, sampler if variant != "no_replay" else None
            )
            R_exact[i, j] = exact_acc
            R_para[i, j] = para_acc
            
            # Aggregate failures and contamination details on the final stage
            if i == num_blocks:
                for r in para_recs:
                    if not r.correct:
                        total_failures += 1
                        if r.is_contaminated:
                            total_contaminations += 1
                    margin_pool.append(r.logit_margin)

        # Evaluate Gating false-positives at the final stage
        if i == num_blocks:
            with torch.no_grad():
                # General control text FPR
                for ctrl in control_texts:
                    ctrl_ids = tokenizer.encode(ctrl, return_tensors="pt").to(hybrid.device)
                    _, ctrl_h = gpt2_forward(hybrid, ctrl_ids)
                    ctrl_q_raw = ctrl_h[0, -min(2, ctrl_h.shape[1]):, :].mean(dim=0).unsqueeze(0)
                    ctrl_q_proj = memory.query_proj(ctrl_q_raw)
                    ctrl_q_read = memory.to_read_space(ctrl_q_proj, mu, V_sub)
                    _, ctrl_sims = memory.slow_mlp(ctrl_q_read)
                    
                    ctrl_gate_prob = torch.sigmoid(
                        memory.gate_sharpness * (ctrl_sims[0, 0] - memory.gate_threshold)
                    ).item()
                    if ctrl_gate_prob >= 0.5:
                        gate_fps += 1

                # Hard negative FPR
                for hn in hard_negatives[:100]:
                    hn_ids = tokenizer.encode(hn, return_tensors="pt").to(hybrid.device)
                    _, hn_h = gpt2_forward(hybrid, hn_ids)
                    hn_q_raw = hn_h[0, -min(2, hn_h.shape[1]):, :].mean(dim=0).unsqueeze(0)
                    hn_q_proj = memory.query_proj(hn_q_raw)
                    hn_q_read = memory.to_read_space(hn_q_proj, mu, V_sub)
                    _, hn_sims = memory.slow_mlp(hn_q_read)
                    
                    hn_gate_prob = torch.sigmoid(
                        memory.gate_sharpness * (hn_sims[0, 0] - memory.gate_threshold)
                    ).item()
                    if hn_gate_prob >= 0.5:
                        hn_fps += 1

    # End experiment CL metrics
    final_exact = [R_exact[num_blocks, j] for j in range(num_blocks)]
    final_para = [R_para[num_blocks, j] for j in range(num_blocks)]
    
    forgetting_exact = [R_exact[j+1, j] - R_exact[num_blocks, j] for j in range(num_blocks - 1)]
    forgetting_para = [R_para[j+1, j] - R_para[num_blocks, j] for j in range(num_blocks - 1)]
    
    avg_recall_exact = np.mean(final_exact)
    avg_recall_para = np.mean(final_para)
    avg_forgetting_exact = np.mean(forgetting_exact) if forgetting_exact else 0.0
    avg_forgetting_para = np.mean(forgetting_para) if forgetting_para else 0.0

    margin_min = np.min(margin_pool) if margin_pool else 0.0
    margin_5th = np.percentile(margin_pool, 5) if margin_pool else 0.0
    margin_50th = np.percentile(margin_pool, 50) if margin_pool else 0.0
    margin_95th = np.percentile(margin_pool, 95) if margin_pool else 0.0

    training_time = time.time() - start_time
    bytes_per_fact = sampler.payload_bytes() / len(all_facts) if (variant != "no_replay" and sampler is not None) else 0.0

    return {
        "variant": variant,
        "avg_recall_exact": avg_recall_exact,
        "avg_recall_para": avg_recall_para,
        "avg_forgetting_exact": avg_forgetting_exact,
        "avg_forgetting_para": avg_forgetting_para,
        "failures": total_failures,
        "contaminations": total_contaminations,
        "gate_fps": gate_fps,
        "hn_fps": hn_fps,
        "margin_min": margin_min,
        "margin_5th": margin_5th,
        "margin_50th": margin_50th,
        "margin_95th": margin_95th,
        "bytes_per_fact": bytes_per_fact,
        "training_time": training_time,
    }

# ---------------------------------------------------------------------------
# Main Execution Loop
# ---------------------------------------------------------------------------
def main():
    args = parse_args()
    print("=" * 80)
    print(f"  AGNIS SCALING BENCHMARK: {args.blocks} blocks × {args.facts_per_block} facts")
    print(f"  Seeds to run: {args.seeds} | Epochs: {args.epochs}")
    print("=" * 80)

    # Load 100 Facts dataset
    if not os.path.exists("agnis_scaling_dataset.json"):
        raise FileNotFoundError("Run python generate_scaling_dataset.py first to generate the dataset!")

    with open("agnis_scaling_dataset.json", "r") as f:
        full_blocks = json.load(f)

    # Slice block list based on CLI arguments
    blocks = full_blocks[:args.blocks]
    for b in range(len(blocks)):
        blocks[b] = blocks[b][:args.facts_per_block]
    
    all_facts = [f for b in blocks for f in b]
    print(f"  Total facts to consolidate: {len(all_facts)} across {len(blocks)} blocks.")

    # Initialize model foundation once
    hybrid = build_hybrid()
    tokenizer = hybrid.tokenizer
    hybrid.eval()

    # Pre-consolidated query projection setup
    vocab_size = hybrid.gpt2.config.vocab_size
    memory = EpisodicFactMemory(vocab_size=vocab_size, pool_len=2, device=DEVICE)

    # Run query-projection training on ALL facts upfront to freeze coordinate space
    print("\n[Protocol A] Training query projection on all facts upfront...")
    fact_ranges = {}
    answer_ids_all = {}
    
    for b_idx, block in enumerate(blocks):
        for f in block:
            fid = f["id"]
            # Store templates and answer
            templates = [f["statement"], f["qa"], f["cloze"]]
            for idx, text in enumerate(templates):
                ids = tokenizer.encode(text + tokenizer.eos_token, return_tensors="pt").to(hybrid.device)
                _, h_full = gpt2_forward(hybrid, ids)
                h = memory.pool_sequence(h_full)
                prompt_ids = tokenizer.encode(f["probe"])
                
                n = 0
                limit = min(len(prompt_ids), len(ids[0].tolist()))
                while n < limit and ids[0, n].item() == prompt_ids[n]:
                    n += 1
                boundary = max(0, n - 1)
                h_answer = h[0, boundary:-1, :]
                v_answer = ids[0, boundary + 1:]
                
                start_idx = len(memory)
                memory.write(h_answer, v_answer)
                
                tag = ["_stmt", "_qa", "_cloze"][idx]
                fact_ranges[fid + tag] = (start_idx, h_answer.shape[0])
                if idx == 0:
                    fact_ranges[fid] = (start_idx, h_answer.shape[0])
                    answer_ids_all[fid] = v_answer.detach()

    q_fact, pos_idx = collect_scaling_fact_queries(hybrid, memory, fact_ranges, answer_ids_all, all_facts)
    q_ctrl = collect_control_states(hybrid, memory)
    train_query_projection(memory, q_fact, pos_idx, q_ctrl)
    for param in memory.query_proj.parameters():
        param.requires_grad = False
    print("  [OK] Query projection frozen.")

    # Lock geometry
    temp_keys = []
    for block in blocks:
        for f in block:
            templates = [f["statement"], f["qa"], f["cloze"]]
            for text in templates:
                ids = tokenizer.encode(text + tokenizer.eos_token, return_tensors="pt").to(hybrid.device)
                _, h_full = gpt2_forward(hybrid, ids)
                h = memory.pool_sequence(h_full)
                prompt_ids = tokenizer.encode(f["probe"])
                n = 0
                limit = min(len(prompt_ids), len(ids[0].tolist()))
                while n < limit and ids[0, n].item() == prompt_ids[n]:
                    n += 1
                boundary = max(0, n - 1)
                temp_keys.append(h[0, boundary:-1, :])

    memory.keys_raw = torch.cat(temp_keys, dim=0)
    mu, V_sub = memory.read_space()
    memory.keys_raw = torch.empty(0, 768, device=DEVICE)
    memory.values = torch.empty(0, dtype=torch.long, device=DEVICE)
    memory._space_cache = (mu, V_sub)
    print("  [OK] Read space cache locked.")

    # -----------------------------------------------------------------------
    # Variants Execution Loop
    # -----------------------------------------------------------------------
    results_by_variant = {v: [] for v in args.variants}

    seeds = [1000 * (s + 1) for s in range(args.seeds)]

    for seed in seeds:
        print(f"\n" + "="*80)
        print(f"  RUNNING SEED: {seed}")
        print("="*80)
        
        # Shuffle block execution order for block permutation evaluation
        shuffled_blocks = copy.deepcopy(blocks)
        random.Random(seed).shuffle(shuffled_blocks)

        for variant in args.variants:
            res = run_scaling_experiment(
                variant=variant,
                blocks=shuffled_blocks,
                hybrid=hybrid,
                base_memory=memory,
                mu=mu,
                V_sub=V_sub,
                all_facts=all_facts,
                epochs=args.epochs,
            )
            results_by_variant[variant].append(res)

    # -----------------------------------------------------------------------
    # Print Aggregated Results Summary
    # -----------------------------------------------------------------------
    print("\n" + "="*110)
    print("  AGGREGATED SCALING RUNNER SUMMARY (Across seeds)")
    print("="*110)
    hdr = (f"  {'Variant':<22} {'A_T^ex':>9} {'A_T^pa':>9} {'F_T^ex':>9} {'F_T^pa':>9}"
           f" {'Fails':>6} {'Contam':>7} {'Gate FP':>7} {'HN FP':>6} {'Min m':>7} {'Bytes/F':>8}")
    print(hdr)
    print("  " + "─" * 105)

    for variant, runs in results_by_variant.items():
        avg_rec_ex = np.mean([r["avg_recall_exact"] for r in runs]) * 100
        std_rec_ex = np.std([r["avg_recall_exact"] for r in runs]) * 100
        avg_rec_pa = np.mean([r["avg_recall_para"] for r in runs]) * 100
        std_rec_pa = np.std([r["avg_recall_para"] for r in runs]) * 100
        
        avg_f_ex = np.mean([r["avg_forgetting_exact"] for r in runs]) * 100
        avg_f_pa = np.mean([r["avg_forgetting_para"] for r in runs]) * 100
        
        fails = int(np.mean([r["failures"] for r in runs]))
        contam = int(np.mean([r["contaminations"] for r in runs]))
        gate_fp = int(np.mean([r["gate_fps"] for r in runs]))
        hn_fp = int(np.mean([r["hn_fps"] for r in runs]))
        
        min_margin = np.mean([r["margin_min"] for r in runs])
        bytes_f = int(runs[0]["bytes_per_fact"])

        print(
            f"  {variant:<22}"
            f" {avg_rec_ex:>4.1f}±{std_rec_ex:<3.1f}"
            f" {avg_rec_pa:>4.1f}±{std_rec_pa:<3.1f}"
            f" {avg_f_ex:>8.1f}%"
            f" {avg_f_pa:>8.1f}%"
            f" {fails:6d}"
            f" {contam:7d}"
            f" {gate_fp:7d}"
            f" {hn_fp:6d}"
            f" {min_margin:>+7.2f}"
            f" {bytes_f:8d}"
        )
    print("="*110)

if __name__ == "__main__":
    import functools
    print = functools.partial(print, flush=True)
    main()
