"""
audit_generator_defects_and_leakage.py
=======================================

Audits the exact generator bugs and corrected test-train leakage.
Steps Correction 1 & Correction 2.
"""

import json
import collections

DATASET_PATH = "agnis_scaling_dataset.json"


def get_prompt_only(f, idx):
    if idx == 0:
        return f["probe"]
    elif idx == 1:
        prefix = f["qa"].split(f["statement"])[0]
        return prefix + f["probe"]
    else:
        return f["cloze"].split("_____")[0].strip()


def run_audit():
    print("==================================================")
    print(" CORRECTION 1 & 2 — GENERATOR DEFECTS & LEAKAGE")
    print("==================================================")

    with open(DATASET_PATH, "r", encoding="utf-8") as file:
        blocks_data = json.load(file)

    facts = [fact for b in blocks_data for fact in b]
    total_facts = len(facts)

    # CORRECTION 2: Generator Bug Counts
    b1_statement_in_qa_count = 0
    b2_cloze_equals_probe_count = 0

    for f in facts:
        if f["statement"] in f["qa"]:
            b1_statement_in_qa_count += 1
        cloze_prefix = f["cloze"].split("_____")[0].strip()
        if cloze_prefix == f["probe"]:
            b2_cloze_equals_probe_count += 1

    print(f"\n--- CORRECTION 2: GENERATOR BUG AUDIT ---")
    print(f"  B1: Facts where statement is substring of qa: {b1_statement_in_qa_count} / {total_facts} (Expected: 0)")
    print(f"  B2: Facts where cloze.split('_____')[0].strip() == probe: {b2_cloze_equals_probe_count} / {total_facts} (Expected: 100)")

    # CORRECTION 1: Corrected Leakage Audit
    total_test_queries = 0
    leaked_test_queries = 0
    fact_leak_counts = []
    fact_train_duplicate_counts = []

    for f in facts:
        # Actual 3 train strings generated by get_prompt_only(f, 0..2)
        train_prompts = [get_prompt_only(f, 0), get_prompt_only(f, 1), get_prompt_only(f, 2)]
        train_set = set(train_prompts)

        # Check train duplicates (how many of the 3 train strings are duplicates of each other)
        num_unique_train = len(train_set)
        num_train_duplicates = 3 - num_unique_train
        fact_train_duplicate_counts.append(num_train_duplicates)

        # Test queries: probe + 3 eval_paraphrases (4 test strings total per fact)
        test_strings = [f["probe"]] + f.get("eval_paraphrases", [])
        fact_leak = sum(1 for ts in test_strings if ts in train_set)

        total_test_queries += len(test_strings)
        leaked_test_queries += fact_leak
        fact_leak_counts.append(fact_leak)

    corrected_leakage_fraction = leaked_test_queries / total_test_queries if total_test_queries > 0 else 0.0

    print(f"\n--- CORRECTION 1: CORRECTED LEAKAGE AUDIT ---")
    print(f"  Total test queries evaluated across all facts: {total_test_queries}")
    print(f"  Total test queries appearing verbatim in get_prompt_only train prompts: {leaked_test_queries}")
    print(f"  Corrected Global Test-Train Leakage Fraction: {corrected_leakage_fraction:.4f} ({corrected_leakage_fraction*100:.2f}%)")

    print(f"\n  Per-fact test leakage distribution (out of 4 test strings per fact):")
    leak_dist = collections.Counter(fact_leak_counts)
    for k in sorted(leak_dist.keys()):
        print(f"    {k} / 4 test strings leaked: {leak_dist[k]} facts")

    print(f"\n  Per-fact train string duplication distribution (out of 3 train strings per fact):")
    train_dup_dist = collections.Counter(fact_train_duplicate_counts)
    for k in sorted(train_dup_dist.keys()):
        print(f"    {k} duplicate train strings (out of 3): {train_dup_dist[k]} facts")


if __name__ == "__main__":
    run_audit()
