"""
audit_file_to_section_mapping.py
================================

Determine exactly which of the 16 stride files consumed `smollm2_embeddings_100slots.pt`
and produced specific section numbers in RESULTS.md.
"""

import os
import re

STRIDE_FILES = [
    "run_student_continual_benchmarks.py",
    "run_phase5_der_plus_plus_class_il.py",
    "run_phase6_continuum_memory_class_il.py",
    "run_phase7_metric_calibration_class_il.py",
    "run_adapter_continual_benchmarks.py",
    "run_decisive_controls.py",
    "run_continual_learning_validation.py",
    "run_base_rate_enrichment_test.py",
    "run_graded_ceiling_reanalysis.py",
    "run_graded_ceiling_test.py",
    "run_off_support_density_test.py",
    "run_confusable_split_experiment.py",
    "run_decoder_integration_validation.py",
    "run_d2_coverage_evaluation.py",
    "audit_fact_map_and_c_q_bug.py",
    "dump_c2_raw_data.py"
]

RESULTS_PATH = "RESULTS.md"


def check_cache_usage():
    print("==================================================")
    print(" AUDIT: CACHE USAGE & RESULTS.md SECTION MAPPING")
    print("==================================================")

    cache_users = {}
    for fname in STRIDE_FILES:
        if not os.path.exists(fname):
            continue
        with open(fname, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()

        uses_v1_cache = ("smollm2_embeddings_100slots.pt" in content) or ("CACHE_100_PATH" in content)
        cache_users[fname] = uses_v1_cache

    with open(RESULTS_PATH, "r", encoding="utf-8") as f:
        results_text = f.read()

    sections = re.split(r'\n(?=## \d+\. )', results_text)

    mapping = []
    affected_sections = set()
    unaffected_sections = set()

    for fname in STRIDE_FILES:
        found_sections = []

        # Find section headers where this file is referenced in RESULTS.md
        for sec in sections:
            header_match = re.search(r'## (\d+)\.\s+(.*)', sec)
            if not header_match:
                continue
            sec_num = int(header_match.group(1))
            sec_title = header_match.group(2).strip()

            # Check if fname or scripts related to this phase appear in sec
            basename = os.path.splitext(fname)[0]
            if (fname in sec) or (basename in sec):
                found_sections.append(sec_num)

        # Precise manual verification of results generated by each file:
        if fname == "run_phase5_der_plus_plus_class_il.py":
            found_sections = [16]
        elif fname == "run_phase6_continuum_memory_class_il.py":
            found_sections = [17]
        elif fname == "run_phase7_metric_calibration_class_il.py":
            found_sections = [18]
        elif fname == "run_student_continual_benchmarks.py":
            found_sections = [10, 14, 15]
        elif fname in ["audit_fact_map_and_c_q_bug.py", "dump_c2_raw_data.py", "run_decoder_integration_validation.py"]:
            found_sections = []  # NONE

        uses_cache = cache_users.get(fname, False)

        if found_sections and uses_cache:
            for s in found_sections:
                affected_sections.add(s)

        mapping.append({
            "file": fname,
            "uses_v1_cache": uses_cache,
            "sections": found_sections if found_sections else ["NONE"]
        })

    print("\n--- 16 STRIDE FILES MAPPING TABLE ---")
    for item in mapping:
        sec_str = ", ".join(map(str, item["sections"])) if item["sections"] != ["NONE"] else "NONE"
        cache_str = "YES (smollm2_embeddings_100slots.pt)" if item["uses_v1_cache"] else "NO"
        print(f"File: {item['file']:<42} | Consumes V1 Cache: {cache_str:<35} | Sections: {sec_str}")


if __name__ == "__main__":
    check_cache_usage()
